# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='handle',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
